# Configuration options are documented at:
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - '0.10'
  - '0.12'
  - '4.0'
  - '4.1'
  - '4.2'
  - '4.3'
  - '5.0'
  - '5.1'
  - '5.2'
  - '5.3'
  - '5.4'
  - '5.5'
  - '5.6'
  - iojs
before_script:
  - npm install -g bower
  - cd test
  - bower install -f
  - cd ..
